// <auto-generated />
using System;
using EFCoreSqlite;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EFCoreSqlite.Migrations
{
    [DbContext(typeof(EchoglossianDbContext))]
    partial class EchoglossianDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.10");

            modelBuilder.Entity("EFCoreSqlite.Models.BattleTalkMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("DATETIME");

                    b.Property<string>("OriginalBattleTalkMessage")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("OriginalLang")
                        .IsRequired()
                        .HasColumnType("VARCHAR");

                    b.Property<string>("SenderName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("TranslatedBattleTalkMessage")
                        .HasMaxLength(400)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("TranslationLang")
                        .IsRequired()
                        .HasColumnType("VARCHAR");

                    b.Property<DateTime>("UpdatedDate")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("DATETIME");

                    b.HasKey("Id");

                    b.ToTable("battletalkmessages");
                });

            modelBuilder.Entity("EFCoreSqlite.Models.Journal.QuestPlate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("DATETIME");

                    b.Property<string>("OriginalLang")
                        .IsRequired()
                        .HasColumnType("VARCHAR");

                    b.Property<string>("OriginalQuestMessage")
                        .IsRequired()
                        .HasMaxLength(2500)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("QuestName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("TranslatedQuestMessage")
                        .HasMaxLength(2500)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("TranslationLang")
                        .IsRequired()
                        .HasColumnType("VARCHAR");

                    b.Property<DateTime>("UpdatedDate")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("DATETIME");

                    b.HasKey("Id");

                    b.ToTable("questplates");
                });

            modelBuilder.Entity("EFCoreSqlite.Models.TalkMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("DATETIME");

                    b.Property<string>("OriginalSenderNameLang")
                        .IsRequired()
                        .HasColumnType("VARCHAR");

                    b.Property<string>("OriginalTalkMessage")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("OriginalTalkMessageLang")
                        .IsRequired()
                        .HasColumnType("VARCHAR");

                    b.Property<string>("SenderName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("TranslatedSenderName")
                        .HasMaxLength(100)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("TranslatedTalkMessage")
                        .HasMaxLength(400)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("TranslationLang")
                        .HasColumnType("VARCHAR");

                    b.Property<DateTime>("UpdatedDate")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("DATETIME");

                    b.HasKey("Id");

                    b.ToTable("talkmessages");
                });

            modelBuilder.Entity("EFCoreSqlite.Models.ToastMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("DATETIME");

                    b.Property<string>("OriginalLang")
                        .IsRequired()
                        .HasColumnType("VARCHAR");

                    b.Property<string>("OriginalToastMessage")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("ToastType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("TranslatedToastMessage")
                        .HasMaxLength(200)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("TranslationLang")
                        .IsRequired()
                        .HasColumnType("VARCHAR");

                    b.Property<DateTime>("UpdatedDate")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("DATETIME");

                    b.HasKey("Id");

                    b.ToTable("toastmessages");
                });
#pragma warning restore 612, 618
        }
    }
}
